[Kat-Coder 35B]
model = /home/ava/LLMs/KAT-Coder-V2.5-Dev-APEX-I-Quality.gguf
fitt = 512
fit-ctx = 150000
cache-type-k = q8_0
cache-type-v = q8_0

[Qwen 3.8 27B Ridge]
model = /home/ava/LLMs/Qwen3.8-27B-Ridge-3.7bpw.gguf
ctx-size = 60000
n-gpu-layers = -1
cache-type-k = q8_0
cache-type-v = q8_0
spec-type = draft-mtp
spec-draft-n-max = 1

[Qwen 3.8 Flash Next]
model = /home/ava/LLMs/Qwen_3.8_flash_next/Qwen3.8-Flash-Next-UD-IQ4_XS-00001-of-00003.gguf
fitt = 512
fit-ctx = 60000
cache-type-k = q8_0
cache-type-v = q8_0
spec-type = draft-mtp
#spec-draft-model = /home/ava/LLMs/Qwen_3.8_flash_next/mtp-Qwen3.8-Flash-Next-Q4_K_M.gguf
#spec-draft-n-max = 2
